name: Java CI 02 for deploy artifacts
run-name: ${{ github.actor }} will deploy artifacts 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - uses: actions/checkout@v3
      # Run Docker Compose up
      - name: docker compose
        run: docker compose up -d
      # setup node environment
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # install current dependencies in sub-directory
      - name: install dependencies
        working-directory: ./app
        run: npm install
      # run current tests in sub-directory
      - name: run tests
        working-directory: ./app
        run: npm test
  docker-release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # will push to docker repository
      - name: Build and push to public repository
        uses: docker/build-push-action@v3
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-node:latest